import pandas as pd
import numpy as np
import os
import glob
from shutil import which
from snakemake.utils import validate, min_version
import itertools
import configparser


##### set minimum snakemake version #####
min_version("9.17.2")

##### load config and sample sheets #####

configfile: "config/config.yaml"

yap_config = configparser.ConfigParser()
yap_config.read(config['yap_config'])

config['chrom_sizes'] = yap_config['contact']['chrom_size_path']


units = pd.read_table(config["units"], dtype={"fq1" : str, "fq2" : str})
if not (units['fq1'].is_unique and units['fq2'].is_unique):
    raise Exception('Same fastq specified in more than one row.')

all_units_fastqs = units['fq1'].tolist() + units['fq2'].tolist()
all_raw_data_fastqs = [os.path.basename(fn) for fn in glob.glob('raw_data/*.fastq.gz')]

if any(fq not in all_units_fastqs for fq in all_raw_data_fastqs):
    raise Exception("There are fastqs in raw_data/ that are not listed in config/samplesheet/units.tsv.")

if any(fq not in all_raw_data_fastqs for fq in all_units_fastqs):
    raise Exception("There are fastqs in config/samplesheet/units.tsv that are not in raw_data/.")

units['fq_pref'] = units['fq1'].str.replace('_R1_001.fastq.gz', '')

# regions and quantifier settings for allcools prepare_dataset
prepare_dataset_config = pd.read_table(config["allcools_regions_and_quantifiers_tsv"], dtype={"region_name" : str, "regions" : str, "quantifiers" : str})

snakemake_dir = os.getcwd() + "/"

# make a tmp directory for analyses
tmp_dir = os.path.join(snakemake_dir, "tmp")
if not os.path.exists(tmp_dir):
    os.mkdir(tmp_dir)



rule all:
    input:
        expand("results/generate_mcds/{region_names}/", region_names = prepare_dataset_config['region_name'])

include:
    'rules/yap.smk'
